services:
  - type: web
    name: food-scanner-web
    env: python
    buildCommand: |
      # Install Python dependencies
      pip install -r requirements.txt
      # Install Node.js
      curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
      apt-get install -y nodejs
      # Build frontend
      cd frontend
      npm install
      npm run build
      cd ..
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: NODE_VERSION
        value: 18.0.0 